version: '2'
services:
  code:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    depends_on:
      - datastores
    links:
      - mysql
      - postgres
  # This needs to wait for the datastores to have finished coming up and are
  # actually ready for traffic. q.v. https://github.com/vishnubob/wait-for-it
  datastores:
    image: hello-world
    depends_on:
      - mysql
      - postgres
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
