FROM robkinyon/sims_loader_base:latest
MAINTAINER Rob Kinyon rob.kinyon@gmail.com

ENV app /app
RUN mkdir -p $app
WORKDIR $app

COPY "devops/MyConfig.pm" "/root/.cpan/CPAN/MyConfig.pm"
COPY "devops/within_carton" "/usr/local/bin/within_carton"
RUN chmod +x /usr/local/bin/within_carton

ENTRYPOINT [ "/usr/local/bin/within_carton" ]
CMD [ "prove" ]
