version: '2'
services:
  code:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    depends_on:
      - datastores
    links:
      - mysql
    entrypoint:
    # Uncomment this line to do any of the below options.
      - /usr/local/bin/within_carton
    # Uncomment this line to run specific tests.
      - prove
      - -v
    #  - t/02_loader.t
      - t/03_load.t
    #  - t/05_drivers.t
    #  - t/06_model.t
    # Uncomment this line to get test-coverage statistics.
    #  - cover
  # This needs to wait for the datastores to have finished coming up and are
  # actually ready for traffic. q.v. https://github.com/vishnubob/wait-for-it
  datastores:
    image: hello-world
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
