#!/bin/bash

export MSYS_NO_PATHCONV=1
export COMPOSE_CONVERT_WINDOWS_PATHS=1

DIR=$(git rev-parse --show-toplevel)
cd $DIR

# q.v. http://stackoverflow.com/a/24067243/1732954
function is_minimum_version () {
  [[ "$1" == "$2" ]] && return 0
  [[ "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1" ]]
}

# Validate the docker-compose version >= 1.9.0 on Windows so that the
# "docker-compose run" works.
min_dc_version="1.9.0"

# Assumption: will get "docker-compose version 1.9.0, build 2585387"
dc_version=$(docker-compose --version | cut -f1 -d, | cut -f 3 -d' ')
if ! is_minimum_version $dc_version $min_dc_version; then
  >&2 echo "$dc_version is not at least ${min_dc_version}"
  exit 1
fi

# This ensures the databases are up.
docker-compose up -d datastores

# This launches the sims_loader container
# Note: This assumes you have done `./run_tests` so the containers and network
# are setup as expected below.
docker run \
  --rm \
  --volume $(pwd):/data \
  --network simsloader_default \
  --link simsloader_mysql_1:mysql \
    robkinyon/sims_loader:0.000006 $@
