#!/bin/bash

# On Windows, don't convert the paths from Unix format to Windows format.
# Otherwise, docker volume attachment will fail miserably.
export MSYS_NO_PATHCONV=1

if [[ "$@" == "stop" ]]; then
  docker-compose down
else
  # This order is so that we can launch the databases and let them live beyond
  # any given test run.

  # This is idempotent, so do it every time.
  docker-compose up -d datastores

  # TODO: Add waits to ensure that the databases are ready to take traffic.

  # This runs the tests
  docker-compose up code
fi
